### ISSUE TITLE
No Title Shown

### ISSUE THREAD

**Issue by jamiesin** [tobyweston/radiate#31]
For builds that have a long name, I am just getting a blank green / red box (no title / label). Only when I hover over them can I see a small yellow label indicating what build it is.

**Comment by tobyweston** [comment]
That's intended behavior at the moment for aggregated builds as it's supposed to encourage people to investigate the failure, regardless of what build it is. 

I may change that for chessboard style (like your screenshot) but am closing the issue for now in the interest of prioritizing work.

**Comment by tobyweston** [comment]
See #10
