### ISSUE TITLE
UnknownHostException: https

### ISSUE THREAD

**Issue by SQUIDwarrior** [tobyweston/radiate#35]
Our TeamCity server URL is "https://my.company.com/teamcity". When set this as the TEAMCITY_HOST and try and start radiate, it fails with an "UnknownHostException: https"

**Comment by tobyweston** [comment]
Try setting your `TEAMCITY_HOST` to `my_company.com/teamcity` (exclude the `https` part).

It will default to port `8111`, add another environment property `TEAMCITY_PORT` if that's not yours.

What does the log show?

Also, TeamCity will have to have guest authentication switched on (although you can configure a username/password later). See the README.

**Comment by SQUIDwarrior** [comment]
Removing the "https" gives me a ConnectionRefused error as it is trying to go to "http://my_company.com/teamcity" and not "https://my_company.com/teamcity". The server is using the default https port (443). I did try setting TEAMCITY_PORT to 443, but got the same error as it keeps trying to go to "http" and not "https"

**Comment by tobyweston** [comment]
Ah you've uncovered a bug I think. It supports only `http` at the moment not `https`.

See https://github.com/tobyweston/radiate/blob/master/src/main/java/bad/robot/radiate/teamcity/Server.java

I'll fix that.

I'm working on a version 2 so will include it then if not before.

**Comment by tobyweston** [comment]
Fixed in v2.0
